# config/routes.yaml

add:
    path: /add
    controller: App\Controller\ApiController::add

csv:
    path: dbs/foo/tables/{tableName}/csv
    controller: App\Controller\ApiController::csvApi
    methods: GET